[package]
name = "arcade-core"
description = "The UI-independent text editing engine for ArcadeEdit."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ropey.workspace = true

[lints]
workspace = true

